version: 2.1

executors:
  golang:
    docker: 
      - image: circleci/golang

commands:
  build:
    steps:
      - run:
          name: Build
          command: GOOS=linux GOARCH=amd64 go build
  unit_test:
    steps:
      - run:
          name: Unit Test
          command: go test

jobs:
  validate:
    executor: golang
    steps:
      - checkout
      - build
      - unit_test
      - persist_to_workspace: 
          root: .
          paths:
            - ./contract-test
  deploy:
    executor: golang
    steps:
      - checkout
      - attach_workspace: 
          at: .
      - run: pwd && ls -lah
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(./contract-test --version)
            echo ${VERSION}
            echo ${GITHUB_TOKEN}
            mkdir artifacts
            cp ./contract-test ./artifacts
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  contract-test_workflow:
    jobs:
      - validate
      - deploy:
          requires:
            - validate
          filters:
            branches:
              only: master